export const GET_CONSTRUCTOR_INGREDIENTS = 'GET_CONSTRUCTOR_INGREDIENTS';

export const GET_INGREDIENT_DETAILS = 'GET_INGREDIENT_DETAILS';
export const DELETE_INGREDIENT_DETAILS = 'DELETE_INGREDIENT_DETAILS';

export const GET_ORDER_NUMBER = 'GET_ORDER_NUMBER';
export const UPDATE_ORDER_NUMBER = 'UPDATE_ORDER_NUMBER';